### ISSUE TITLE
Does not support Content Security Policy (CSP) nonce, only unsafe-inline css

### ISSUE THREAD

**Issue by dzsoundnirvana** [fullcalendar/fullcalendar#4317]
Cannot use "script-src 'nonce-...." only supports "style-src 'self' 'unsafe-inline';"

In fullcalendar.js starting at line 11408:
```
// Generates an HTML attribute string for setting the width of the axis, if it is known
    AgendaView.prototype.axisStyleAttr = function () {
        if (this.axisWidth != null) {
            return 'style="width:' + this.axisWidth + 'px"'; <--------- violation will not load
        }
        return '';
    };
```
![calnoncecsponlyunsafeinline_15sep18](https://user-images.githubusercontent.com/3346180/45590351-58b6cb00-b8eb-11e8-90a5-4b1c1ed024ce.PNG)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or explain how to reproduce the error? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by codemasterover9000** [comment]
We have the same problem. This can be fixed by using `element.style.width = this.axisWidth + 'px';`

**Comment by halfninja** [comment]
Demo:

https://codepen.io/halfninja/pen/dgRPzK

In the HTML head I've added the below, which adds a Content Security Policy (normally it would be an HTTP header). The long hashes in here are just to allow the main fullcalendar CSS and demo CSS to load in CodePen. 

`<meta http-equiv="Content-Security-Policy" content="style-src 'self' 'sha256-3wE6om7wsjgmaEcN8PeaBW8gFRhfuO4E3h37DMXo3cM=' 'nonce-EDNnf03nceIOfn39fn3e9h3sdfa'">`

You will see the problem in the console when you switch to _week_ and _day_ views, as it refuses to apply anything provided as a style attribute:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-3wE6om7wsjgmaEcN8PeaBW8gFRhfuO4E3h37DMXo3cM=' 'nonce-EDNnf03nceIOfn39fn3e9h3sdfa'". Either the 'unsafe-inline' keyword, a hash ('sha256-aqNNdDLnnrDOnTNdkJpYlAxKVJtLt9CtFLklmInuUAE='), or a nonce ('nonce-...') is required to enable inline execution.

Adding `'unsafe-inline'` isn't an option because that undermines the whole point of CSP. @codemasterover9000 has the general idea, though I know that this is not easy in practice because of how fullcalendar uses strings of HTML to pass everything around. It would be a lot easier to fix if it created DOM elements and passed those around.

To be honest I can't actually tell any visual difference with or without these width styles being set, so I'm not sure how necessary they are.

If you're only setting a small subset of styles like width, then a workaround could be to set a data attribute like `data-width=40px` and then once you have dropped everything into the document, search for any elements with that attribute and copy the value to `element.style.width`. Might sound a bit hacky but would avoid having to completely redesign how the library renders stuff.

**Comment by acerix** [comment]
Thanks for the detailed report and demo.

**Comment by poradz** [comment]
Current version (4.2.0) contains another  CSP bug:
Refused to load the font 'data:application/x-font-ttf;charset=utf-8;base64 [...] because it violates the following Content Security Policy directive: "default-src 'self' blob:". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

![image](https://user-images.githubusercontent.com/31520119/61362172-08e5bf00-a882-11e9-9d56-9a37b22d6f5d.png)

It's caused by loading remote src url in @font-face in the core main.css file.

Please correct it, in order to  [YetiForceCRM](https://github.com/YetiForceCompany/YetiForceCRM) could use the newest version without css modification of forking ;)

**Comment by arshaw** [comment]
Can someone please post literature about what "nonce" is any why it doesn't allow DOM manipulation in this way?

**Comment by halfninja** [comment]
Nonces are explained here - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

In summary they are only for script tags, not style attributes, and it requires the server side to generate a new nonce for every HTTP request.

The only fix for style attributes containing variable styles is to replace them with the style property.

CSP is becoming the norm for deployments and is no longer a 'weird' environment.

**Comment by vandernorth** [comment]
@halfninja couldn't mention a visual bug, but besides the errors in the console I've found that when using a CSP the `color` attribute on an event on the dayGrid (and possibly others) doesn't work anymore. 

The best fix would be to change all codepaths that return a html-string containing `style=` to return an HTMLDomElement. Or @halfninja's suggestion using `data-*` attributes which I might even like better. 

Another options (specific to the color issue I mentioned) would be to allow a `className(s)` in the same places where `color` is allowed in which case the style attribute can be omitted and I become responsible for my own styling.

**Comment by vandernorth** [comment]
I've created a PR with a possible fix for this issue.

**Comment by arshaw** [comment]
this is fixed [in the latest v5-beta](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

thanks @vandernorth , your fix will be valuable for v4

**Comment by arshaw** [comment]
this is no longer an issue in v5, which has [just been released](https://fullcalendar.io/blog/2020/06/v5-official)

**Comment by xi** [comment]
Unfortunately this is not fixed. In `main.js` (fullcalendar-scheduler@5.1.0) I still find 4 instances of `style="…"`, for example here:

https://github.com/fullcalendar/fullcalendar/blob/d1250398ef4fedd1cacb9979b4c61ad2344e5bad/packages/common/src/util/table-styling.ts#L19

**Comment by acerix** [comment]
I can confirm 5.1.0 still uses "unsafe-inline" CSS from the example in https://github.com/fullcalendar/fullcalendar/issues/5556.

![Screenshot_2020-06-29_15-49-26](https://user-images.githubusercontent.com/379534/86049919-02b00a80-ba21-11ea-88d4-c1a5ef054c30.png)

**Comment by arshaw** [comment]
I've fixed this and queued it for the next release, but there was one part of the code I couldn't completely convert to a "safe" inline execution: the `data:` font-family in https://cdn.jsdelivr.net/npm/fullcalendar@5.1.0/main.css

There seem to be two solutions for this:

1. whitelist all data: urls like `<meta http-equiv="Content-Security-Policy" content="default-src 'self' data:;" />`
2. only apply the protection to script tags like `<meta http-equiv="Content-Security-Policy" content="script-src 'self'" />`

Are either of those two solutions good enough for people? Do some people have environments that they don't have complete control over where they can't relax the CSP this much?

PS- I'm not sure how I'd remove the inlined glyph font

**Comment by xi** [comment]
>  I'm not sure how I'd remove the inlined glyph font

Would it be possible to serve the font as a separate file? That way it would be covered by 'self'. Another alternative would be to replace it with inline SVG.

**Comment by arshaw** [comment]
Using inline SVGs seems like a more portable solution.

I'll look into this more, and accept more feedback of course, but this is a substantial enough change where I won't have it done before the release this week. I will still release my other CSP fixes though.

**Comment by vandernorth** [comment]
Just a little feedback: In my environment (and others I know) I would be quite acceptable to include `data:` in the CSP whitelist. It's a lot safer than `unsafe-inline` anyhow.

**Comment by arshaw** [comment]
This has been released in v5.2.0

If you have problem with the `data:` font, please upvote this issue: https://github.com/fullcalendar/fullcalendar/issues/5685 . It proposes FullCalendar switch to inline SVG icons.

**Comment by goulvench** [comment]
If you still have an error after enabling `unsafe-inline` styles, make sure that your setup doesn't include nonces for styles, because they prevent nonce-free styles from being applied. 

**Example policy with nonces:**
```
Content-Security-Policy: base-uri 'self'; [other values…] style-src 'self' https: 'unsafe-inline' 'nonce-zO0MwPmzV7TY0vV2KZrIVg=='
```

**Example policy _without_ nonces:**
```
Content-Security-Policy: base-uri 'self'; [other values…] style-src 'self' https: 'unsafe-inline'
```
