### ISSUE TITLE
[alpha2] drop not firing when dragging between calendars

### ISSUE THREAD

**Issue by Skyless7** [fullcalendar/fullcalendar#4348]
Drop not firing while draging event from one calendar to another. eventRecieve works while eventLeave doesnt exist in optionsInput. 
Docs say 'When dropped, the eventLeave, drop, and eventReceive callbacks will fire.'

Feels like installation version of fc alpha2 over npm is not the same as these one's here.

this is the config of both calendars
`header: {
                    left: '',
                    center: '',
                    right: ''
                },
                editable: true,
                selectable: true,
                droppable: true,
                firstDay: 1,
                slotDuration: {
                    minutes: 15
                },
                slotLabelInterval: {
                    minutes: 15
                },
                slotLabelFormat: {
                    hour: 'numeric',
                    minute: '2-digit',
                    omitZeroMinute: false,
                    meridiem: 'short',
                    hour12: false
                },
                allDaySlot: false,
                columnHeaderFormat: {
                    weekday: 'short',
                    day: 'numeric',
                    month: 'numeric'
                },
                slotEventOverlap: true,
                displayEventEnd: false,
                defaultView: 'agendaDay',
                minTime: {
                    hours: 6,
                    minutes: 0
                },
                maxTime: {
                    hours: 22,
                    minutes: 0
                },
                dragScroll: true,
                nowIndicator: true,
                handleWindowResize: true,
                timeZone: 'local',
                navLinks: true,
                weekNumbers: true,
                height: 'auto',
                eventSources: [ this.eventList ],
                drop: (dropInfo) => {
                    console.log('drop');
                    console.log(dropInfo);
                },
                eventReceive: (info) => {
                    this.calService.modifyActionPointDateOnDragDropWithDifferentOwner(info);
                }`

Interesting enough, when external element is dropped to calendar , drop callback fires, but from calendar to calendar not. 

Inspecting fullcalendar.d.ts for drop and eventReceive shows this below, while the arguments are totally different in the fullcalendar.js. eventLeave doesnt exist in fullcalendar.d.ts.
I do have latest version of fullcalendar.d.ts

drop?(arg: {
	        date: DateInput;
	        allDay: boolean;
	        jsEvent: MouseEvent;
	    }): void;
eventReceive?(event: EventApi): void;

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by Skyless7** [comment]
https://codepen.io/anon/pen/gBjRaR?editors=1111

So eventReceive and eventLeave fires, while drop does not, so i dont have the information where i dropped the event i was dragging, therefore i cannot replace his date and time in the database.

Only drop includes date of where the event was dropped and i'm not having it fired.

**Comment by Skyless7** [comment]
To be even more precise in describing the issue,
I am using "fullcalendar": "^4.0.0-alpha.2" as explained. 

In v4 docs in section Dragging Between Calendars on this url: https://fullcalendar.io/docs/v4/other-calendar-dragging
It is said "When dropped, the eventLeave, drop, and eventReceive callbacks will fire."
- In my case eventLeave and eventReceive callbacks fire, while drop does not. And only drop contains the information about time and date where we dropped event (date | The Date of where the draggable was dropped)

drop callback fires when we use External Event Dragging.

I have even recordered a video of my example https://www.youtube.com/watch?v=Jq-2T79yULk
I have both editable and draggable true in all of calendars (in example, there are three day calendars). While dragging event from one calendar to another, eventRecieve and eventLeave callbacks fire, while drop does not, and i have no information of new time where event was dropped and therefore i cannot update it.
@acerix

**Comment by acerix** [comment]
Thanks for the demo and detailed report.  Yes, `drop` should be firing according to the docs you linked.

**Comment by jlyman** [comment]
@acerix or anyone else, has work started on this? If not, I might look at opening up a PR because I need this in short order.

**Comment by Skyless7** [comment]
This is quite a big bug which makes whole functionality of dragging events between multiple calendars totaly useless. Hopefully a temporary workaround of permanent fix will come soon enough.

**Comment by jlyman** [comment]
(As a side question, why was it determined that `drop` wouldn't also carry the Event Object as well? Seems like to properly affect a change with a dropped event you have to listen to both `drop` and `eventReceive` and collect necessary info from both separately and asynchronously in order to do something with a dropped event.)

**Comment by arshaw** [comment]
i see why this is broken. i'll get it fixed for the next alpha release.

@jlyman , what information do you need from `drop` that you can't get from `eventReceive`? FYI, the `info.event` property in [eventReceive](https://fullcalendar.io/docs/v4/eventReceive) is the event object that has been mutated to hold the new start/end/allDay/resource.

**Comment by arshaw** [comment]
the problem with `drop` not firing in this scenario has been fixed: fd3e878202668e5df6167c875897acbe89a04073
(in the v4 branch)

I'll comment on this issue again when released

**Comment by jlyman** [comment]
> @jlyman , what information do you need from `drop` that you can't get from `eventReceive`? FYI, the `info.event` property in [eventReceive](https://fullcalendar.io/docs/v4/eventReceive) is the event object that has been mutated to hold the new start/end/allDay/resource.

I believe I was seeing issues where the new start/end date hadn't been mutated in the event object upon `eventReceive`, but I could be wrong on that as I can't wholly remember. If that's not the case then disregard.

(Doing a quick check with the [draggable demo](https://fullcalendar.io/docs/v4/other-calendar-dragging-demo) doesn't show a mutated start/end date on the event object on `eventReceive`, but is it mutated after the even fires?)

**Comment by arshaw** [comment]
this has been addressed and released in [4.0.0-alpha.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.0-alpha.4)

`drop` now fires in this circumstance

**Comment by Mihai-github** [comment]
Hi, still having this issue after one drag next one does not get triggered... any idea why?
