### ISSUE TITLE
[V4] Locale files not changing header button text

### ISSUE THREAD

**Issue by AlexPaTruco** [fullcalendar/fullcalendar#4581]
Hello,

I'm on V4 and ran to an issue when using script tags for locales. I basically included the es-us.js file into my HTML, also set the locale option on my calendar object to 'es-us' and the calendar translates days and months just fine. However, it's not translating the header buttons.

![image](https://user-images.githubusercontent.com/6219340/55009840-9478ce80-4fb9-11e9-8d15-f55f71efb3dc.png)

I was following the docs instructions. Is there anything that I'm missing?

Thanks!

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Here's a demo showing the translations are working:

https://fullcalendar.io/docs/locale-demo

The locale is called "es" so might not work if you set it to "es-us".

**Comment by AlexPaTruco** [comment]
> Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
> 
> Here's a demo showing the translations are working:
> 
> https://fullcalendar.io/docs/locale-demo
> 
> The locale is called "es" so might not work if you set it to "es-us".

I was able to solve it by including the locales-all.js file in my html, just like in the demo you sent. However, the problem still persists if I only include the locales/es.js file. Thanks, for the help!

**Comment by azeos** [comment]
The same thing is happening to me. If you replace `locales-all.js` with `es.js` and set the locale to `es`, it doesn't work. All the translated strings of the file are ignored.

https://codepen.io/anon/pen/mgdbVE

**Comment by arshaw** [comment]
confirmed, thanks

**Comment by arshaw** [comment]
fixed in [v4.0.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.2)!

updated codepen to prove it: https://codepen.io/arshaw/pen/WWQRpd?editors=0010

this bug only showed itself when using script tags and browser globals

**Comment by jotae1e** [comment]
I am using angular 8 and this bug is still present

**Comment by raffiki113** [comment]
I can confirm that this issue is still present in the latest version of fullcalendar.
I am trying to use the german locale (de)

**Comment by shelkem** [comment]
Same issue here

**Comment by DavidsGT** [comment]
Debes importar `locales-all.min.js` como en mi caso estoy usando angular fullCalendar importe en angular.js `"./node_modules/@fullcalendar/core/locales-all.min.js"`, tenia el mismo problema y asi fue como lo solucione. Espero ayudar. Comparto fragmento de codigo:

**Comment by edika99** [comment]
Same problem on 4.4.0 with scripts tags

**Comment by FelixPriori** [comment]
Same problem using React.js

```
<FullCalendar
  //...
  locale={'fr'}
  //...
/>
```

Won't update that pesky 'all-day'. I was able to manually change the `today`, `dayGridMonth`, `timeGridWeek`, and `timeGridDay` to French using the `buttonText` method (which is not ideal), but not the `all-day` one.

**Comment by valentineloyko** [comment]
same here :( doesn't translate buttons in React.js. Please, reopen the bug

**Comment by emil-malmgaard-rasmussen** [comment]
Same problem with danish

Package JSON:
`"dependencies": {
    "@fullcalendar/core": "^5.3.1",
    "@fullcalendar/daygrid": "^5.3.0",
    "@fullcalendar/interaction": "^5.3.0",
    "@fullcalendar/react": "^5.3.0",
    "react": "^16.13.1",
    "typed-rest-client": "^1.7.3"
  },
`
In the represented view:
`
import da from '@fullcalendar/core/locales/da';
import dayGridPlugin from '@fullcalendar/daygrid'
import interactionPlugin from '@fullcalendar/interaction';
import FullCalendar from '@fullcalendar/react'

...
<FullCalendar
                locale={'da'}
                plugins={[dayGridPlugin, interactionPlugin]}
                headerToolbar={{
                    left: 'prev,next today',
                    center: 'title',
                    right: ''
                }}
                ...
            />
`

**Comment by floatingpurr** [comment]
Setting `locale: 'it'` does not translate text in buttons

**Comment by ceimox** [comment]
Same issue here using NextJS what I had to do was:
1) install the core `npm i @fullcalendar/core`
2) import the locals depending on your verison, you might need to review your node_modules to see what is exported there
3) import them into your component
    ```
    import esLocale from "@fullcalendar/core/locales/es-us"
    import enLocale from "@fullcalendar/core/locales/en-nz"
    ```
4) send the available locals to your component
```
  return (
    <FullCalendar
      locales={[esLocale, enLocale]}
      locale={language}
```
5) in the other hand, if you prefer not to install the core just for this, you could also create the proper locale constants and use them, such as:

```
const esLocale = {
    code: "es",
    week: {
      dow: 0, // Sunday is the first day of the week.
      doy: 6, // The week that contains Jan 1st is the first week of the year.
    },
    buttonText: {
      prev: "Ant",
      next: "Sig",
      today: "Hoy",
      month: "Mes",
      week: "Semana",
      day: "Día",
      list: "Agenda",
    },
    weekText: "Sm",
    allDayText: "Todo el día",
    moreLinkText: "más",
    noEventsText: "No hay eventos para mostrar",
  }

  return (
    <FullCalendar
      locales={[esLocale]}
      locale={language}
  ```
  The english local is taken by default you don't require to override it

**Comment by alexofx** [comment]
Utilicen ese enlace en sus script, a mi me funciono y locale: 'es' en un javacript.
     <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.9.0/locales-all.js"></script>
Saludos...

**Comment by dcruz1990** [comment]
How can i change the locale on custom buttons? can't find it on docs. Tried `setOptions("customButtons", { buttonNme: { text: "text" }})` but doesnt works

**Comment by tanhongit** [comment]
> Utilicen ese enlace en sus script, a mi me funciono y locale: 'es' en un javacript. <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.9.0/locales-all.js"></script> Saludos...

Thank you, for adding this script to fix the problem in my case.

**Comment by AsaphF** [comment]
> Same issue here using NextJS what I had to do was:
> 
> 1. install the core `npm i @fullcalendar/core`
> 2. import the locals depending on your verison, you might need to review your node_modules to see what is exported there
> 3. import them into your component
>    ```
>    import esLocale from "@fullcalendar/core/locales/es-us"
>    import enLocale from "@fullcalendar/core/locales/en-nz"
>    ```
> 4. send the available locals to your component
> 
> ```
>   return (
>     <FullCalendar
>       locales={[esLocale, enLocale]}
>       locale={language}
> ```
> 
> 5. in the other hand, if you prefer not to install the core just for this, you could also create the proper locale constants and use them, such as:
> 
> ```
> const esLocale = {
>     code: "es",
>     week: {
>       dow: 0, // Sunday is the first day of the week.
>       doy: 6, // The week that contains Jan 1st is the first week of the year.
>     },
>     buttonText: {
>       prev: "Ant",
>       next: "Sig",
>       today: "Hoy",
>       month: "Mes",
>       week: "Semana",
>       day: "Día",
>       list: "Agenda",
>     },
>     weekText: "Sm",
>     allDayText: "Todo el día",
>     moreLinkText: "más",
>     noEventsText: "No hay eventos para mostrar",
>   }
> 
>   return (
>     <FullCalendar
>       locales={[esLocale]}
>       locale={language}
> ```
> 
> The english local is taken by default you don't require to override it

Thanks for the solution, helped me on a Vue.js project

**Comment by ismail-hamdach** [comment]
I am using nextJs 13.4.13 and fullcalendar 6.1.8 and this bug is still present but if I do:

import fr from "@fullcalendar/core/locales/fr";

<FullCalendar
        ....
        locale={fr} />
then it works well.

**Comment by santiagoaguero** [comment]
> Utilicen ese enlace en sus script, a mi me funciono y locale: 'es' en un javacript. <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.9.0/locales-all.js"></script> Saludos...

great, this worked for me, thanks
