### ISSUE TITLE
Header button "today" doesn´t get translated to locales pt and pt-br

### ISSUE THREAD

**Issue by virgilioneves** [fullcalendar/fullcalendar#4591]
Issue can be easily replicated at https://fullcalendar.io/docs/locale-demo

Looking at locales-all.js file I see the proper translation is there ("Hoje") but associated with a different property called "currentText". In other working locales the equivalent property used is called "today". Please, see highlighted bellow:
 
`var _m48 = {
        code: "pt-br",
        buttonText: {
            prevText: "Anterior",
            nextText: "Próximo",
            **currentText**: "Hoje",
            month: "Mês",
            week: "Semana",
            day: "Dia",
            list: "Compromissos"
        },
        weekLabel: "Sm",
        allDayText: "dia inteiro",
        eventLimitText: function (n) {
            return "mais +" + n;
        },
        noEventsMessage: "Não há eventos para mostrar"
    };
`

**Comment by virgilioneves** [comment]
Just notice the same behaviour for header buttons Prev and Next for locales pt and pt-br

**Comment by arshaw** [comment]
confirmed. wrong keys in the translation file:
https://github.com/fullcalendar/fullcalendar/blob/master/locales/pt-br.js

should be `next` instead of `nextText`, etc. i will check other locales for this problem as well

**Comment by arshaw** [comment]
fixed in [v4.0.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.2)!

**Comment by MyosotisArae** [comment]
I use the 4.0.2 version. I have set the locale to 'fr', and all the calendar was translated in french, except for the button "today". If I change 'today' in 'zzz' in the variable RAW_EN_LOCALE in main.js, then the button's label is 'zzz'.

**Comment by alexisplogg** [comment]
I'm using the 4.3.1 version, and the problem is still there. 
I have set the locale to 'fr'. Everything gets translated except for the "today" button.

**Comment by jbgury** [comment]
I have the same issue, do you know if it will be fixed with the locale 'fr' ?

**Comment by gongAll** [comment]
@MyosotisArae @alexisplogg @jbgury 

The button text is not translated when the locale is set. More info [here](https://fullcalendar.io/docs/buttonText). I will just give you the use case of my application. You have to do something like this for a multilingual application:
```
export const localeButtonText: Object = {
  'en-US': {
    today: 'today',
    year: 'year',
    month: 'month',
    week: 'week',
    day: 'day',
    list: 'list'
  }, // default value
  'pt-PT': {
    today: 'hoje',
    year: 'ano',
    month: 'mês',
    week: 'semana',
    day: 'dia',
    list: 'lista'
  },
'fr': {
    today: '...',
    year: '...',
    month: '...',
    week: '...',
    day: '...',
    list: '...'
},
...
};
```
and bind the buttonText value to each of them, according to the currently chosen language. So when you set locale='fr', you also set buttonText=localeButtonText['fr']. I believe this will solve it for you.

**Comment by jbgury** [comment]
:+1: 
Yes, indeed, it works. Thank you a lot

**Comment by dcruz1990** [comment]
I'm having similar issue, but with 'es', 'de', 'tr', locales. I'll try the @gongAll solution on this.

**Comment by marcofloriano** [comment]
Had to translate this part of the plugin manually like that:

buttonText: {
        prev: "<",
        next: ">",
        prevYear: "<<",
        nextYear: ">>",
        today: "Hoje",
        month: "Mês",
        week: "Semana",
        day: "Dia"
      }
