### ISSUE TITLE
Events disappear when navigating between months quicker than the event source is fetched

### ISSUE THREAD

**Issue by doublemix** [fullcalendar/fullcalendar#4975]
### Issue

I am using version 4.3.0 with a month view. I have one asynchronous data source. When I navigate away from a month and quickly back to it (before next month's events return from server), some or all events from this month disappear. It only causes a problem when your data source is slow enough.

Screenshots:

| Before Nav / Expected | After Quick Nav (Bug) |
| --- | --- |
| ![Before / Expected](https://user-images.githubusercontent.com/32748075/62973035-4d15a200-bde3-11e9-8481-5b6bb5b506e9.PNG) | ![After Quick Nav Bug](https://user-images.githubusercontent.com/32748075/62973036-4d15a200-bde3-11e9-92e0-2ddc2aa38f6e.PNG) |

I know this is very similar to #3920, but that issue was closed and my set-up is different than his. (sorry, if it is).

### Reproduction

I have a reproduction here: [FullCalendar Bug #4975 Demonstration](https://doublemx2-fullcalendar-bug3920.herokuapp.com/). It's a Heroku app because I needed a custom server. Here's the repo, in case you want to see the set-up: [doublemix/fullcalendar-bug-4975](https://github.com/doublemix/fullcalendar-bug-4975)

### Suspected Cause

I believe the cause is in [`core/reducers/eventSources`](https://github.com/fullcalendar/fullcalendar/blob/0141b3d496f63d789424cd6d25e2776b370ed117/packages/core/src/reducers/eventSources.ts#L76-L98)

When you navigate back to a month before the next month has finished loading, `fetchDirtySources` and `isSourceDirty` don't find any dirty sources (since this month's data is still there), and therefore `latestFetchId` is not updated. Then, when the response comes back, since the `latestFetchId` is still the same, the calendar replaces this month's events with next month's (in [`receiveResponse`](https://github.com/fullcalendar/fullcalendar/blob/0141b3d496f63d789424cd6d25e2776b370ed117/packages/core/src/reducers/eventSources.ts#L186-L191)), making it appear as though they are disappearing.

### Workaround

I found that disabling lazy fetching fixes the problem because then the sources are always dirty.

**Comment by acerix** [comment]
Thanks for the detailed report and workaround, confirmed.

**Comment by arshaw** [comment]
i fixed this and released it in v4.4.0
https://github.com/fullcalendar/fullcalendar/releases/tag/v4.4.0

**Comment by arshaw** [comment]
https://github.com/fullcalendar/fullcalendar/commit/e1621994aa39737c32615185c12ae03cb5288a25

**Comment by shamseerahammedm** [comment]
This issue still exists, this happens when user clicks next button or moves to different view when events are fecting , this is only happening when there are a lot of events in the calendar. is there anyway to disable buttons when events are fetching 

```
  useEffect(() => {
        if (eventFetching)
        {
            document.querySelectorAll('.fc-button').forEach(elem => {
                elem.disabled = true;
                
                elem.classList.add("disableClick");  
            });
        }
        if (!eventFetching)
        {
            // setTimeout(()=>{
                document.querySelectorAll('.fc-button').forEach(elem => {
                   
                    elem.classList.remove("disableClick"); 
                    elem.disabled = false;
                });
            // },800)
            
        }
    }, [eventFetching, addEventLoading, isDeleting, isRSVPFetching])

```

this is the work around i tried  so far  but fails, button is working even when disabled attribute is added...
any ideas how to do this ??
