### ISSUE TITLE
Calendar does not render correctly on first render using the Angular component in Ionic

### ISSUE THREAD

**Issue by pramodjb** [fullcalendar/fullcalendar#4976]
Hi there,

As usual I am getting the data from API and assigning the same to "Event Input" array as shown below.

fillCalendar(start, end) {
    this.auth.Appointment(start, end).subscribe(
      data => {
        this.calendarEvents = [];
        data.map((timeSlot, index) => {
          let day = { index, title: timeSlot.name, start: new Date(timeSlot.startTime), end: new Date(timeSlot.endTime), schoolId: timeSlot.schoolId, SchoolName: timeSlot.schoolName, comments: timeSlot.comments, uniqueId: timeSlot.uniqueId };
          this.calendarEvents = this.calendarEvents.concat(day);
        })
      }
    )
  }

However, during the initial loading though the events are bound to the calendar, they are hidden some where. However, the events gets shown without running any code when doing the following actions,

1) Open developer tool(F12) and close it.
2) Click on next or previous navigation. 

Please let me know if any further details are required. Any help here would be greatly appriciable.

![fullcalendar](https://user-images.githubusercontent.com/13535859/62997907-5bb59500-be87-11e9-9f84-b3fa0feaf4fc.PNG)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by pramodjb** [comment]
Hi Acerix,

Thanks for the response. Below are the steps to be followed after downloading.

1) Unzip to some location.
2) Open the command prompt and browse to the folder in which it is unzipped.
3) Run "npm install" to install all the required packages.
4) Run "npm start" to run the project.
5) Browse to the url "http://localhost:4200/calendar".

[Sample Ionic-FullCalendar.zip](https://github.com/fullcalendar/fullcalendar/files/3525253/Sample.Ionic-FullCalendar.zip)

**Comment by acerix** [comment]
Thanks for the demo. I can see the issue which was also reported in our support inbox. https://fullcalendar.freshdesk.com/a/tickets/1076

There is no component for Ionic though, and I believe Ionic support is outside the scope of the Angular component, so will leave this issue open as a feature request for Ionic support.

The problem is that the Angular component calls `render()` from `ngAfterViewInit`, but in Ionic that is too early, I think it needs to be called from `ionViewDidLoad` instead.

The calendar renders correctly if `render()` is called after the page is loaded, for example by resizing the window.

I don't know a good way to fix that in Ionic but this hack to trigger a resize seems to work ok:

```ts
ngOnInit() {
    setTimeout( function() {
        window.dispatchEvent(new Event('resize'))
    }, 1)
}
```

**Comment by bfwg** [comment]
I wrok around was to add a setTimeout around `getApi().render();`
```
setTimeout(() => {
  this.fullcalendar.getApi().render();
});
```

**Comment by arshaw** [comment]
we'll need a repro in codesandbox.io before we can move ahead with a fix

**Comment by 5im0n** [comment]
@arshaw, 

I just create a [Stackblitz demo](https://stackblitz.com/edit/ionic-angular-fullcalendar-gatjnq) of the bug.

The first render is broken. 
When we rerender the calendar by clicking on a button (next, prev for instance) or updating an option with a timeout, everything is great.

I don't have this problem with Angular only app, so it may be related with Ionic.

**Comment by BrunoLucarelli056** [comment]
I'm seeing this issue as well, in an Angular 10 app with Angular Material library. No Ionic.

**Comment by kubanm3** [comment]
I have two tabs, when you reload site on the other tab then switch to calendar it doesn't render correctly.
![image](https://user-images.githubusercontent.com/22613738/94695719-8cc88180-0336-11eb-9090-6c4f284bbc07.png)

**Comment by arshaw** [comment]
@kubanm3 , could you try calling `calendar.updateSize()` after the tab switch?

**Comment by kubanm3** [comment]
It works first time, but then if you switch back and again it is wrong again.

`window.dispatchEvent(new Event('resize'));` works each time, but there is a short time just after first switch where calendar is wrongly rendered. Then it fixes and stays good.

**Comment by rocifier** [comment]
I just tried to use fullcalendar in angular and mine looks the same as @kubanm3's screenshot. There are no rows, and the columns are squished. After trying a few of these hacks, I got the columns to not look squished on top of one another, but I still see now rows or times

**Comment by LarsVanderheydt** [comment]
Had the same issue in ionic too (worked perfectly without ionic), got it working by calling the `.getApi().render()` in `ionViewWillEnter` without any `setTimeout`.

**Comment by rocifier** [comment]
Hi, we are depending on this in production now and it has started breaking using window resize event. I have motivation to help fix this. If anyone can point me to the correct render flow I may be able to fix it and submit a PR

**Comment by rocifier** [comment]
> Had the same issue in ionic too (worked perfectly without ionic), got it working by calling the .getApi().render() in ionViewWillEnter without any setTimeout.

I tested this out in my "heavyweight" app which loads two full calendar components at once. It worked for one of them but not for the other one.

**Comment by LarsVanderheydt** [comment]
@rocifier we're still in development with our fullcalendar implementation so can't really tell you with 100% certainty if it's a production-ready solution, but we hadn't had the issue since the fix in development.

For the fullcalendar that doesn't seem to work, maybe the component you're implementing the `ionViewWillEnter` on isn't an ionic page? Lifecycles aren't triggered in child components of an ionic page, if that's the issue you should use [this fix](https://forum.ionicframework.com/t/lifecycle-hooks-for-inner-components/69095/4).

**Comment by rocifier** [comment]
> @rocifier we're still in development with our fullcalendar implementation so can't really tell you with 100% certainty if it's a production-ready solution, but we hadn't had the issue since the fix in development.
> 
> For the fullcalendar that doesn't seem to work, maybe the component you're implementing the `ionViewWillEnter` on isn't an ionic page? Lifecycles aren't triggered in child components of an ionic page, if that's the issue you should use [this fix](https://forum.ionicframework.com/t/lifecycle-hooks-for-inner-components/69095/4).

Thanks for your reply. The ionViewWillEnter function is being called once and at that time I am asking both calendars to render(). When I inspect the components in a debugger I noticed they both have isRendering: true on the api objects already, I don't know if this means anything. I have now verified that the reason the big calendar works is because later on (around 1 second later) I am updating the events on that one. I have temporarily got both calendars working by taking the point in time that I update the large calendar's events and scheduling a window resize event then. Obviously a very inelegant solution, and the whole page jolts around after a second or two, but it always resolves itself when changing to other tabs and back also.

**Comment by LarsVanderheydt** [comment]
@rocifier is it possible to send me a minimal, reproducible example? I tried to render two calendars inside a component on a fresh **ionic** install and it seemed to work perfectly with `.getApi().render().` At first the second calendar didn't render properly because I was using `ViewChild` instead of `ViewChildren` but otherwise it's working.

**Comment by rocifier** [comment]
> @rocifier is it possible to send me a minimal, reproducible example? I tried to render two calendars inside a component on a fresh **ionic** install and it seemed to work perfectly with `.getApi().render().` At first the second calendar didn't render properly because I was using `ViewChild` instead of `ViewChildren` but otherwise it's working.

Unfortunately not, the problem only occurs using your solution when the app gets quite complex and slows down. I'm making a variety of api calls and some of the calendar event sources are loading in at different times, for example. I also have other tabs loading content in the background.

**Comment by rocifier** [comment]
> @rocifier is it possible to send me a minimal, reproducible example? I tried to render two calendars inside a component on a fresh **ionic** install and it seemed to work perfectly with `.getApi().render().` At first the second calendar didn't render properly because I was using `ViewChild` instead of `ViewChildren` but otherwise it's working.

Can you explain what you mean by it not working when you use ViewChild instead of ViewChildren? Because I am using ViewChild twice with two different ids for my calendars

**Comment by LarsVanderheydt** [comment]
@rocifier if you're using the `ViewChild` twice with an `id` you should be fine, I worked with `ViewChildren` like this:
```
@ViewChildren(FullCalendarComponent) fullCalendars: FullCalendarComponent[];

this.fullCalendars.forEach(fullCalendar => fullCalendar.getApi().render());
```

**Comment by diegoramirez19** [comment]
Hello everybody, I'm having the same error right now, when the app load at first time, the Calendar not render correctly, I did all of test above but It doesn't work yet.
If someone can help me, it would be great.
![image](https://user-images.githubusercontent.com/36805899/147370499-a08f5c54-e00f-47a4-a638-20da95feebc8.png)

**Comment by diegoramirez19** [comment]
Hello Guys, I was able to fix it.
I was working with angular 9 and Ionic 5, I updated all dependencies (Angular 9 to Angular 13) (Ionic 5 to Ionic 6).
One thing to keep in mind is the use of the encapsulation, because in my project I have several pages and I used encapsulation in one of my components, as a result the calendar styles didn't work correctly  
`selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.scss'],
  encapsulation: ViewEncapsulation.None` 
Remenber keep in mind this, because it's could be your problem

**Comment by BartKalkman** [comment]
I have this issue aswell but in React. It renders all day names (eg. monday) all the way in the upper left corner over each other and does not render a body. Is there a fix for this already?

**Comment by stefanosisto** [comment]
> I have this issue aswell but in React. It renders all day names (eg. monday) all the way in the upper left corner over each other and does not render a body. Is there a fix for this already?

Hello, I have the same issue in React.
Did you find any solution?
For now, I'm trying with `window.dispatchEvent(new Event('resize'))`... but for 1 second I'm able to see the "broken" calendar and this sound very bad... Please let me know how you have solved it

**Comment by tekman-oppsec** [comment]
> > I have this issue aswell but in React. It renders all day names (eg. monday) all the way in the upper left corner over each other and does not render a body. Is there a fix for this already?
> 
> Hello, I have the same issue in React. Did you find any solution? For now, I'm trying with `window.dispatchEvent(new Event('resize'))`... but for 1 second I'm able to see the "broken" calendar and this sound very bad... Please let me know how you have solved it

To get around this I did a setTimeout to call a click event on the month button after the calendar.render(). 

setTimeout(clickMonthButton, 100);
function clickMonthButton() {
    document.querySelector('.fc-dayGridMonth-button').click();
}

**Comment by realappie** [comment]
@acerix Given we have a reproduction path in #7221, do you think anyone on the team has capacity to pick this up? The calendar is almost unusable in its current state. I'm considering to get the 'Premium' package to get access to resource view, but this bug is holding me off doing that purchase.

**Comment by JohannesPertl** [comment]
Any idea when this will be fixed?

**Comment by arshaw** [comment]
Fixed in [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5)

Updated repro: https://stackblitz.com/edit/ionic6-angular13-xcrctf?file=src%2Fapp%2Fapp.module.ts,package.json

We will eventually make the calendar adapt to dimensions changes via ResizeObserver as [mentioned in this ticket](https://github.com/fullcalendar/fullcalendar/issues/5507). However, in the meantime, I needed to [write ionic special-case logic in the angular connector](https://github.com/fullcalendar/fullcalendar-angular/commit/99ec38a31db71503a718c20a36146fa59b3007ef) which doesn't feel good but works.

**Comment by AlexisEspejo** [comment]
Hi, I am currently using full calendar version 6.1.8 in angular 15 and the loading problem is happening to me when navigating between components that does not load and only loads when I do a refresh.  

<img width="806" alt="image" src="https://github.com/fullcalendar/fullcalendar/assets/66917532/8d7b3d1b-f087-48bf-a690-5caf29cb8f62">

**Comment by Lo2aiAmer** [comment]
I'm still facing this issue with Angular, did anyone had luck with this ?

**Comment by esultanovvalley** [comment]
Have the same issue in react 17. 
Using this work around

```
  useEffect(() => {
    window.setTimeout(() => {
      window.dispatchEvent(new Event("resize"));
    }, 75);
  });
```

**Comment by mylifeandcode** [comment]
Having this problem now with Angular 17 and @fullcalendar/angular 6.1.10.

**Comment by MrUpsidown** [comment]
I am using the Vue3 component with fullcalendar @fullcalendar/vue3@6.1.8 and have a similar issue. I can see the calendar display fine, then the events are loaded, then the width of the calendar is some 20px wider than it should, which hides the day numbers on the far right side. Dispatching a resize event also fixes the issue.

**Comment by mylifeandcode** [comment]
> Having this problem now with Angular 17 and @fullcalendar/angular 6.1.13.

For me, the issue was happening if I loaded the calendar from a tab component when the calendar was on a tab which was not the active one. My workaround was to use the event which handles tab changes to trigger the calendar reload based on a variable set to indicate the reload was needed.

**Comment by hardikT309** [comment]
I didn't get the Saturday column when first time FullCalender render. 

  // Force re-render of the calendar after mounting
  useEffect(() => {
    setTimeout(() => {
      setCalendarKey(calendarKey + 1);
    }, 100);
  }, []);
  
  I use this but still it doesn't get Saturday for first time calender render.
