### ISSUE TITLE
Change timezone doesn't affect recurring event start/end time.

### ISSUE THREAD

**Issue by bbagdad** [fullcalendar/fullcalendar#5273]
Hi,

I am using fullcalendar with angular, with "**timeGridWeek**", I have recurring events that contain **starttime** and **endtime** as Duration Parsable strings.
the bug is when I change the **timezone** these events doesn't update in the view. they stay on the same timeslot they where at.

I've tried to recreate it on codepen.. but not with Angular on the below link.
https://codepen.io/bbagdad/pen/bGdgRza?editors=0010

**Comment by acerix** [comment]
Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.

The timezone setting only updates event positions if the events are provided by a server and the server does converts the times according to that param.  You need a plugin to do that on the client side:

https://fullcalendar.io/docs/timeZone#with-a-timezone-plugin

**Comment by bbagdad** [comment]
I used the moment timezone plugin for that matter, and it still didn't work. the problem only occurs on the recurring events, that are expanded by the calendar library. it works normally on the other ones..

**Comment by acerix** [comment]
Thanks for the demo, I can see the timezone plugin is not working for recurring events. 

I also confirmed the same issue in the debug and the same happens with rrule. 

https://codepen.io/acerix/pen/VwLpEWX?editors=0010  (Changing the timezone should also move the recurring events)

**Comment by danaki** [comment]
`timeZone` parameter is still ignored

**Comment by adenta** [comment]
@danaki have you found a workaround? I really don't want to have to rebuild the RRULE string client-side

**Comment by danaki** [comment]
> @danaki have you found a workaround? I really don't want to have to rebuild the RRULE string client-side

Yes, my workaround is to do everything on backend, not relying on calendar tomezone handling. Moment just for string formatting.

**Comment by adenta** [comment]
Like, doing everything on the backend is impossible, no?

On the back-end, I don't know what timezone the user is in. if I send over '1500' to fullcalendar, the event will _always_ be at 3PM, no matter what timezone the user is in.

How can you do everything on the backend, are you tracking the users timezone there?

**Comment by danaki** [comment]
Full callendar sends the timeone when it requests for events so it can be handled on the backend.

**Comment by meness** [comment]
I have the same issue with RRule plugin. `timeZone` will be applied perfectly without that plugin. I work with UTC datetimes, but the calendar doesn't apply given `timeZone`.

**Comment by danilo-augusto** [comment]
I stumbled on this today, so I decided to take a look at the source code, and apparently it is this way by design.

If we look at the code triggered when the timezone is manually changed (`eventStore.ts`), we find:
```js
if (def.allDay || def.recurringDef) {
  return instance // isn't dependent on timezone
} else {
// [...]
```
(cf. [this permalink](https://github.com/fullcalendar/fullcalendar/blob/073417c034f6bfb09a61f03f1aa36fece08ef9b2/packages/common/src/reducers/eventStore.ts#L175))

As we can see recurrent events are treated as independent of the timezone.

This code is only triggered on timezone changes though (hence the name of the function `rezoneEventStoreDates`), and this is called [in the CalendarDataManager.ts](https://github.com/fullcalendar/fullcalendar/blob/073417c034f6bfb09a61f03f1aa36fece08ef9b2/packages/common/src/reducers/CalendarDataManager.ts#L328).

The event parsing magic that deals with timezone for *single* (non-recurring) events apparently comes from the following chain of calls:
1. `parseEvent` (in `event-parse.ts`)
1. `parseSingle` (called only for single events)
1. `context.dateEnv.createMarkerMeta` is called to calculate the start and end dates of the event, where dateEnv is an instance of DateEnv in the file `env.ts`
1. `[DateEnv.]timestampToMarker` is finally called by `createMarkerMeta`, and this function is timezone-aware.

For the recurrent events `parseEvent` will only return a "definition" of the event, since the expansion into real events is done later, by means of `expandRecurring` in `recurring-event.ts`, more specifically `expandRecurringRanges`. This function returns the start dates (the type `DateMarker` is simply an alias to `Date`) of the expanded events. Note that here the `DateEnv` methods used are not timezone-aware (e.g. `DateEnv.add`).

So I think those are the two important places that need changing (the `rezoneEventStoreDates` function and `expandRecurrentRanges`), but I may be wrong, specially this is the first time I look into this codebase...

---

Now I think there are two important points of discussion:

1. Even though this can potentially solve the problem of the "target timezone", it does not allow for a "source timezone", i.e. recurrent events would need to always be converted to UTC before being stored. This is in part because we currently do not even have a way of telling the timezone: we write `startTime: "09:00"`, not `startTime: "09:00+0200"`...
We could just say: "Hey, not a big trouble ¯\_(ツ)_/¯, let's simply store recurrent events in UTC". I would just like to say that this means the change is **not backcompatible**. Current behavior treats recurring events as "timezone-agnostic", and changing this to stored-as-UTC means shifting a lot of timestamps on client-side.
So it's important to be smooth on this. We could for example add a new parameter to the recurrent event definition in order to allow the two behaviors to coexist.

2. It's evident the timezone **cannot** be applied on the recurrent event definition (i.e. before expansion), since timezones are complicated and depend on the exact timestamp being shifted. We have Daylight Saving Time and even political complications (Egypt has changed timezones multiple times in the past). Many people are aware of this here, but I think it's important to state: named timezones are not just fixed offsets like "+0200" that stay the same through time.
So OK, let's say we apply timezone shifts after expanding events (the right way).
Now there's another catch: I can also think of recurrent events that should stay the same regardless of, say, Daylight Saving Time (DST) kicking in... If I add "Lunch at 12:00 everyday" to a calendar, **I probably don't want this to move during DST**. However this is exactly what would have happened if the event was stored in UTC and dynamically shifted after expansion... "Central European Standard Time (CET)" variates between UTC+1 and UTC+2 depending on the time of the year, and so on. So always storing in UTC and forgetting the timezone in which the event was initially created does not seem like the best idea now. 
It's maybe better to add a field (say, `timezoneRecur`) that will store the named timezone (e.g. `Europe/Paris`) in which the event was saved. This way the local nuances are kept and we avoid bad surprises like the one above.

**Comment by jusfeel** [comment]
> > @danaki have you found a workaround? I really don't want to have to rebuild the RRULE string client-side
> 
> Yes, my workaround is to do everything on backend, not relying on calendar tomezone handling. Moment just for string formatting.

Hi, using the backend, the time can be formatted. but there is this "UTC" string auto-attached by calendar. How did you handle it? How to remove it? Or better , show the correct time zone but startTime/endTime can have time zone?

**Comment by zalharash** [comment]
Same issue here, I am trying to enforce timezone despite the client browser's timezone, but `timeZone` option same to be broken and it does nothing, I tried with `@fullcalendar/moment-timezone` and without it.

Language: React
Release: "@fullcalendar/react": "^5.3.1"

**Comment by OliverBalfour** [comment]
We have a monkey patch which seems to work. We're pretty sure it works around daylight savings changeover boundaries and other special cases but haven't tested exhaustively

After importing and before using `rrulePlugin` add this:

```js
// Monkey patch rrulePlugin for FullCalendar to fix https://github.com/fullcalendar/fullcalendar/issues/5273
// (Recurring events don't respect timezones in FullCalendar)
// We simply replace the expand function here: https://github.com/fullcalendar/fullcalendar/blob/ede23c4b2bf0ee0bb2cbe4694b3e899a09d14da6/packages/rrule/src/main.ts#L36-L56
// With a custom version below
rrulePlugin.recurringTypes[0].expand = function (errd, fr, de) {
  return errd.rruleSet.between(
    fr.start,
    fr.end,
    true, // inclusive (will give extra events at start, see https://github.com/jakubroztocil/rrule/issues/84)
  ).map(date => new Date(de.createMarker(date).getTime() + date.getTimezoneOffset() * 60 * 1000))
}
```

In our case with the React fullcalendar component and Luxon + RRule plugins we can then set the `timeZone` prop on `<FullCalendar />` to a string like `Australia/Sydney` and it works as expected

(Snippet is under the MIT license, use how you like)

**Comment by pl4nty** [comment]
+1, I wasn't sure whether returning a date vs createMarker would break anything, but seems fine so far

**Comment by Jorgen-VikingGod** [comment]
I have the same issue. rrule + moment-timezone plugin
f.e.

```
rrule: {
  byweekday: ['th']
  dtstart: "2022-04-14T01:20:00+02:00"
  freq: "weekly"
  interval: 1
},
duration: "01:40"
```

My fullcalendar uses `timeZone: "local"` to show the entries in local time of browser.
All entries are saved as ISO format with UTC-Offset  (like above)

Error case is:
in Germany it should show the entry on Thursday every week on 1:40 AM, but it is shown on Friday at 1:40 AM.
As soon I change the entry to

```
rrule: {
  byweekday: ['th']
  dtstart: "2022-04-14T02:20:00+02:00"
  freq: "weekly"
  interval: 1
},
duration: "01:40"
```
It is shown correctly on Thursday at 2:20 AM.

So I think the issue is, that the timezone UTC offset calculation was done wrong - so in the case of 1:40+02:00 it will land on Wednesday in UTC time, so it will correct it later on by one day, but the calendar then shows it on Friday...

**Comment by jgalb** [comment]
> We have a monkey patch which seems to work. We're pretty sure it works around daylight savings changeover boundaries and other special cases but haven't tested exhaustively
> 
> After importing and before using `rrulePlugin` add this:
> 
> ```js
> // Monkey patch rrulePlugin for FullCalendar to fix https://github.com/fullcalendar/fullcalendar/issues/5273
> // (Recurring events don't respect timezones in FullCalendar)
> // We simply replace the expand function here: https://github.com/fullcalendar/fullcalendar/blob/ede23c4b2bf0ee0bb2cbe4694b3e899a09d14da6/packages/rrule/src/main.ts#L36-L56
> // With a custom version below
> rrulePlugin.recurringTypes[0].expand = function (errd, fr, de) {
>   return errd.rruleSet.between(
>     fr.start,
>     fr.end,
>     true, // inclusive (will give extra events at start, see https://github.com/jakubroztocil/rrule/issues/84)
>   ).map(date => new Date(de.createMarker(date).getTime() + date.getTimezoneOffset() * 60 * 1000))
> }
> ```
> 
> In our case with the React fullcalendar component and Luxon + RRule plugins we can then set the `timeZone` prop on `<FullCalendar />` to a string like `Australia/Sydney` and it works as expected
> 
> (Snippet is under the MIT license, use how you like)



This wasn't exactly what I needed particularly, but, you did point me in the right direction of getting daylight savings errors solved. Thank you so much. 

My fix looks like this : 
```js
rrulePlugin.recurringTypes[0].expand = function (errd, fr, de) {
  const hours = errd.rruleSet._dtstart.getHours();
  return errd.rruleSet.between(de.toDate(fr.start), de.toDate(fr.end), true).map((d) => {
    return new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate(), hours, d.getMinutes()));
  });
};
```
It takes the hours from the `dtstart` option and uses that for all other dates within the rrule.

**Comment by arshaw** [comment]
This has been fixed in [v6.1.6](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.6)

Updated repro:
https://codepen.io/arshaw/pen/RweKOEp?editors=0010
(timed events will shift when timezone changed)

**Comment by arshaw** [comment]
@tedroden, this should be fixed for recurring event as well. Sorry i forgot to update the repro. This updated repro proves it: https://codepen.io/arshaw/pen/RweKOEp?editors=0010

could it be that you don't have a [timezone plugin](https://fullcalendar.io/docs/timeZone#with-a-timezone-plugin) ?

**Comment by tcjens** [comment]
@arshaw - In your pen, it appears that this is still not working.

Am I doing something incorrectly? I didn't modify the pen and the times were still reverting to original timezone when navigating.

Thank you.

**Comment by arshaw** [comment]
@tcjens, you're right, the bug is still present after navigating dates.

Updated repro with latest fc:
https://codepen.io/arshaw/pen/yLWmvwm?editors=0010

I'll get this fixed for the next bugfix release.

**Comment by prabhuraj-dev** [comment]
@arshaw any timeline regarding when we can expect the next bugfix?

**Comment by arshaw** [comment]
I finally fixed this in [v6.1.17](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.17)

Updated repro: https://codepen.io/arshaw/pen/KwKbYNy?editors=0010
(now preserves tz change for recurring events when PREV/NEXT is clicked)
