### ISSUE TITLE
Timeline - Resource AND Column grouping

### ISSUE THREAD

**Issue by aximuseng** [fullcalendar/fullcalendar#5324]
I want to have the rolled up grouped resource AND grouped columns at the same time.

It would look like this:

(https://i.stack.imgur.com/h7jxe.png)

Can't seem to implement this so I guess it's a feature request.

**Comment by acerix** [comment]
I can see setting `group: true` breaks the grouping from `resourceGroupField` so that seems like a bug:

https://codepen.io/acerix/pen/zYGbdGY?editors=0010

**Comment by jasper502** [comment]
Thanks for looking at this.  I was not sure if this was the intended feature or just perhaps no one had considered it being used this way. 👍

BTW very impressed with the Resource Timeline Plug-in.  Once I get the bugs worked out on my end the licence purchase will be forthcoming 💵👍

**Comment by aximuseng** [comment]
Thanks for looking at this. I was not sure if this was the intended feature or just perhaps no one had considered it being used this way. 👍

BTW very impressed with the Resource Timeline Plug-in. Once I get the bugs worked out on my end the licence purchase will be forthcoming 💵👍

**Comment by mgerdt** [comment]
Hello!
Is this feature still on the roadmap? I tried to replicate the view aximuseng described with the screenshot and would be very happy to accomplish this with the plugin.  :)
Will this bug be addressed in one of the next releases?

**Comment by lukassiarny** [comment]
Hello,
This bug is still relevant in FC 6. Are there any plans to fix it please? We have to do some "complicated" DOM manipulations to achieve this behavior.
