### ISSUE TITLE
License key option not working, "Unknown option 'schedulerLicenseKey'" error in console

### ISSUE THREAD

**Issue by dariovinci** [fullcalendar/fullcalendar#5462]
Hello guys, i'm getting this warning with latest beta release: 

 `schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source',`

i didn't find any reference to this option in changelogs

**Comment by acerix** [comment]
Thanks, confirmed.

https://codepen.io/acerix/pen/RwWmzWr?editors=0010

Seems like a bug related to this:

https://github.com/fullcalendar/fullcalendar-scheduler/blob/089b8ea6c99566322b48e24480c2ad5b01445aab/__tests__/src/lib/gpl-key.js#L3

**Comment by arshaw** [comment]
I see what's going on. I'll get this fixed for the next release.

In the meantime, people can use this workaround to hide the warning:

```js
import { BASE_OPTION_REFINERS } from '@fullcalendar/core'
BASE_OPTION_REFINERS.schedulerLicenseKey = String
```

This bug is also preventing the warning message from disappearing in the UI. The above workaround will fix that as well, assuming they're using a valid license key.

**Comment by stan-nahualli** [comment]
Is there any workaround for Angular integration?  Such a workaround not fixes issue in Angular application because of strong typing first of all

**Comment by nathan-rc** [comment]
Also experiencing this issue with the VueJS component.

**Comment by efess** [comment]
> Is there any workaround for Angular integration? Such a workaround not fixes issue in Angular application because of strong typing first of all

Get around this in typescript by casting the type to any

`(BASE_OPTION_REFINERS as any).schedulerLicenseKey = String`

**Comment by arshaw** [comment]
This is fixed in the new [v5 release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features)

**Comment by mniederkofler** [comment]
With the latest release candidate, there still seems to be a problem.
I didn't manage to set my license key. The suggested workaround in the comments didn't help at all.
Anyone else seeing this?

**Comment by arshaw** [comment]
@adenta is saying he has continued problems as well. reopening this issue until I get more clarity.

Could people please go to the [Reduced Test Cases page](https://fullcalendar.io/reduced-test-cases), click the FullCalendar v5 "Scheduler plugins" template, try to enter their license key, and see if that makes the license warning at the bottom go away?

If it doesn't work, please post your email address (or some other information identifying your FullCalendar Scheduler purchase, like domain name) and I'll look up your key and try it myself.

**Comment by mniederkofler** [comment]
I should have added that I am using the Angular integration.
The attribute schedulerLicenseKey is simply not available and it gives a compile error.

> Object literal may only specify known properties, and 'schedulerLicenseKey' does not exist in type 'CalendarOptions'

https://codesandbox.io/s/goofy-mccarthy-pge0e?file=/src/app/app.component.ts

**Comment by acerix** [comment]
Thanks, confirmed that the option doesn't work in Angular.

**Comment by arshaw** [comment]
this bug has finally been fixed in the [official v5](https://fullcalendar.io/blog/2020/06/v5-official)

@mniederkofler , to get your demo to work, i needed to upgrade to official 5.0.0 AND i needed to add a premium plugin (@fullcalendar/timeline). If you don't add a premium plugin, the `schedulerLicenseKey` option is not available.

https://codesandbox.io/s/agitated-morning-o8we6?file=/src/app/app.component.ts

**Comment by fwd079** [comment]
Hi, this is still broken in 5.3.0 despited all premium plugins.
`(BASE_OPTION_REFINERS as any)` solution by @efess worked for me for now.
Kind Regards.

**Comment by F-howk** [comment]
The problem has reappeared，Many options report unknown option errors
Unknown option 'eventLimit'
Unknown option 'dayNamesShort'
...

**Comment by Troy-Yang** [comment]
the same issue persists in the v5.11.0 react of typescript.
The workaround is the way above mentioned:

/* @ts-ignore */
BASE_OPTION_REFINERS.schedulerLicenseKey = String;
/* @ts-ignore */
BASE_OPTION_DEFAULTS.schedulerLicenseKey = SCHEDULER_LICENSE_KEY;

**Comment by mbarmettler** [comment]
sadly its still throwing this message with 6.1.x

**Comment by bivald** [comment]
Is there a work-around for 6.X? The above one doesn't seem to work in TS+React (`The requested module '/node_modules/.vite/deps/@fullcalendar_core.js?v=1e722fc7' does not provide an export named 'BASE_OPTION_DEFAULTS'`)

**Comment by augustofagioli** [comment]
> The problem has reappeared，Many options report unknown option errors Unknown option 'eventLimit' Unknown option 'dayNamesShort' ... ![image](https://user-images.githubusercontent.com/34292531/103602247-7d189480-4f46-11eb-8b05-15701a18af5d.png)

With most recent releases, some options were removed
