### ISSUE TITLE
Fullcalendar.io certificate error

### ISSUE THREAD

**Issue by GregoreLeLynx** [fullcalendar/fullcalendar#5476]
Hi,  
One of your certificate is expired. Modern browser will show your pages anyway but when we use a firewall who do ssl inspection, your site is bloqued. Look at this: https://www.sslshopper.com/ssl-checker.html#hostname=https://fullcalendar.io/ Please, remove the invalid certificate from your chain.  

Thanks

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
I'm really sorry about this @GregoreLeLynx . Apparently my certificate vendor is aware and working on it: https://www.namecheap.com/blog/sectigo-ssl-certificate-root-expiration-issue/?utm_campaign=root-expiration-may-30-2020&utm_content=banner

**Comment by arshaw** [comment]
I'm working on this by attempting to upload a renewed certificate but I'm having some problems. I'll update this ticket when I have an update.

**Comment by arshaw** [comment]
I believe I've fixed this. Could you please verify @GregoreLeLynx ?

**Comment by GregoreLeLynx** [comment]
Sorry, it's not fixed. You can look at this url to check it : 
(https://www.sslshopper.com/ssl-checker.html#hostname=https://fullcalendar.io/)
or this one:
(https://www.ssllabs.com/ssltest/analyze.html?d=fullcalendar.io)

**Comment by arshaw** [comment]
Ok it should be fixed NOW. Could you verify on your own system @GregoreLeLynx ? The tester links you sent me no longer report any errors.

**Comment by GregoreLeLynx** [comment]
Yes, it's working now. Thank you.
