### ISSUE TITLE
support hooks inside Content attributes

### ISSUE THREAD

**Issue by adenta** [fullcalendar/fullcalendar#5523]
https://codesandbox.io/s/goofy-mendeleev-u14p0?file=/src/DemoApp.jsx

So you can't use hooks inside of all of the `Content` things in v5. It would be dope to support them, so we can get really high-quality drop-in's to various parts of fullcalendar

**Comment by adenta** [comment]
do I just need to turn https://github.com/fullcalendar/fullcalendar/blob/e028f8b414059393353da30245103f117404242a/packages/common/src/common/render-hook.tsx into a functional component?

**Comment by arshaw** [comment]
@adenta for some reason you recreation doesn't run for me. also, it looks like it's using v4. could you look into that?

**Comment by adenta** [comment]
The recreation also does not run for me. There is no [v5 template](https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/v5/react?file=/src/DemoApp.jsx), it is broken on your site.

**Comment by adenta** [comment]
But it makes sense. Hooks can only run in functional component, the code I linked you is a class based component

**Comment by arshaw** [comment]
@adenta i've fixed the v5 templates. updated links here: https://fullcalendar.io/reduced-test-cases

**Comment by adenta** [comment]
:/ still not getting anything at https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/v5/react?file=/src/DemoApp.jsx

**Comment by arshaw** [comment]
arggggggg. I'm sorry about that. I updated the links again. Here's a direct link to the React repro: https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/master/react?file=/src/DemoApp.jsx

**Comment by adenta** [comment]
does this work for you?

a hook inside event content breaks stuff

https://codesandbox.io/s/upbeat-rgb-6ilgq?file=/src/DemoApp.jsx

**Comment by arshaw** [comment]
The codepen repro broken again but I revived it by adding the `devServer` line in the webpack config. I might need to fix that across the board. Not your fault.

Once I fixed that, I noticed some things that WERE your fault...
1. the `eventContent={EventContent()}` line shouldn't be a function call. It should be `eventContent={EventContent}`
2. the `event-content.jsx` file didn't import the root React import, so JSX broke

But even after that, hooks still didn't work. FullCalendar's fault.

Here's the furthest I got the repro: https://codesandbox.io/s/sad-dan-gfcl2?file=/src/DemoApp.jsx

I made a workaround that wraps the hook-based component with a function

```jsx
function renderEventContent() {
  return <EventContent />;
}
```

I will still fix the root cause of this bug soon. It seems as though when a function is passed in, FullCalendar doesn't think to interpret it as a component. It might be impossible to create an API that handles a function component in addition to the other [content injection types](https://fullcalendar.io/docs/content-injection) but I'll try.

**Comment by arshaw** [comment]
I'm actually going to change my stance here: we won't allow references to hook-based components for top-level *Content settings. You'll always have to wrap it within a function that returns an instance of one. We'll repurpose this ticket to address the docs.

**Comment by arshaw** [comment]
We shouldn't (and currently don't) allow class-based components for this either. that needs to be in the docs too

**Comment by adenta** [comment]
Can I get a bit more of an explanation? Wrapping the component means there
are some things with effects you just can’t do?

**Comment by adenta** [comment]
I’m happy to add you to my repo so you can get a look at what I’m doing.
Not allowing class or hook based components is definitely going to hold
full calendar back.

**Comment by arshaw** [comment]
You're misunderstanding what I'm saying. Did you see this demo I made for you previously? https://codesandbox.io/s/sad-dan-gfcl2?file=/src/DemoApp.jsx

**Comment by arshaw** [comment]
you can't do this:

```jsx
eventContent={MyComponent}
```

but you can do this:

```jsx
eventContent={function() {
  return (<MyComponent />)
}}
```

**Comment by adenta** [comment]
Alright, we are good here. In the example you gave, there is no passing around of the event props, but it looks like you can more-or-less pass them directly through to the child component.

https://codesandbox.io/s/festive-liskov-3ki3w?file=/src/event-content.jsx

```
eventContent={function({event}) {
  return (<MyComponent event={event} />)
}}
```
