### ISSUE TITLE
Time axis width is lost when project HTML through slotLabelContent

### ISSUE THREAD

**Issue by jamesamuel** [fullcalendar/fullcalendar#5526]
Example case: https://codepen.io/jamesamuel/pen/yLebMPP

The time axis width is lost then projecting html into `slotLabelContent` when `allDaySlot` is set to false.

**Comment by arshaw** [comment]
confirmed. the fix will require making the `fc-timegrid-slot-label-cushion` div `display:inline-block`

**Comment by arshaw** [comment]
this has been fixed in v5.0.1

https://codepen.io/arshaw/pen/bGEWjZG

**Comment by jamesamuel** [comment]
Confirmed, works in the repo, but the issue still seems to exist in `"@fullcalendar/angular": "^5.0.0"`.

`fc-timegrid-slot-label-cushion` div `display:inline-block` is missing.

I was going to reproduce but the sandbox is not working https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/v5/angular?file=/src/app/app.component.ts

**Comment by arshaw** [comment]
sorry about that. i forgot to release a v5.0.1 version of angular. that's on my immediate TODO list

**Comment by arshaw** [comment]
v5.1.0 of angular has been released and it contains the fix
