### ISSUE TITLE
Ability to scroll event popover with many events, bottom is not visible if taller than page

### ISSUE THREAD

**Issue by yuan9090** [fullcalendar/fullcalendar#5532]
**Issue Report**

When I have many event and open popover, the scroll event different then v4.

v4  
When I scroll, the popover and calendar scroll, and I can see all events.
https://codepen.io/yuan9090/full/QWyKrKV

v5
When I scroll, the popover fixed and only calendar scroll, I only see half events and I can't see more.
https://codepen.io/yuan9090/full/BajBNVg

You can check gif and see different: left (v4) vs right (v5)
![Hnet-image](https://user-images.githubusercontent.com/9431852/85437085-9a929c00-b5bc-11ea-814f-dd9e0346e12a.gif)

So, Is it possible same ? Thanks a lot

**Comment by arshaw** [comment]
Hi @yuan9090 , I will come up with a more proper solution soon, but here's a workaround. Add this custom css:

```js
.fc-more-popover {
  max-height: 95%;
  overflow-y: auto;
}
```

https://codepen.io/arshaw/pen/RwrLGry?editors=0110

**Comment by belozer-ti** [comment]
@arshaw https://codesandbox.io/s/fullcalendar-v5-react-forked-vx651?file=/src/DemoApp.jsx (open more and scroll page)

How we can fix the popover position so that it stays within the calendar?

**Comment by arshaw** [comment]
This has been fixed in v5.7.0!
blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570

repro: https://codepen.io/arshaw/pen/RwrLGry?editors=0010

**Comment by k-sai-kiranmayee** [comment]
Hello @arshaw @belozer-ti, is [this](https://github.com/fullcalendar/fullcalendar/issues/5532#issuecomment-813727412) possible now in 5.7.0. Even if I add a height and max-height and set overflow-y to auto/scroll along with -webkit-overflow-scrolling: touch, it is not working in iOS (safari and native app)

Could you help me with this one, please

Thank you!

**Comment by Bengejd** [comment]
I was still having this issue in version 5.8.0, I'm not sure if it's just because of view encapsulation and rendering, but either way. I came up with a pretty sound solution for our purposes if anyone else needs help.

_Note: If you have HMR enabled, it will re-add this event listener every time your app reloads when the component is visible, but this only happens in Dev._

```  public ngAfterViewInit() {
    document.addEventListener("click", (e) => {
      if (this.hasClass(e.target, "fc-more-link")) {
        this.resizePopupBody();
      }
    });
  }

  private hasClass = (elem, className) => elem.className.split(" ")
                                              .indexOf(className) > -1;

  private resizePopupBody = () => {
    const popupBody = Array.from(document.getElementsByClassName("fc-popover-body") as HTMLCollectionOf<HTMLElement>)[0];
    const pos = popupBody.getBoundingClientRect();
    const window_height = window.innerHeight;

    if (pos.bottom > window_height) {
      const newMaxHeight = pos.height - (pos.bottom - window_height);
      popupBody.style.maxHeight = newMaxHeight + "px";
    }
  };```

**Comment by k-sai-kiranmayee** [comment]
Thank you @Bengejd for the response and help :), I'm not sure if that works, however will give it a try, and also I have updated the above [comment](https://github.com/fullcalendar/fullcalendar/issues/5532#issuecomment-870426037). Please let me know if you have any ideas and thank you once again!

**Comment by Bengejd** [comment]
> Thank you @Bengejd for the response and help :), I'm not sure if that works, however will give it a try, and also I have updated the above [comment](https://github.com/fullcalendar/fullcalendar/issues/5532#issuecomment-870426037). Please let me know if you have any ideas and thank you once again!

Glad i could (hopefully) help! We are only targeting web browsers at this time, so I'm unsure if the solution would work for native IOS applications, but I can confirm at least for Chrome, Firefox, and Edge at least. No idea about safari, but I imagine it would work just the same. I'm a little rusty on how IOS handles window height though, so you may have to adapt it a little bit to work with iPhone.

**Comment by linkillhz** [comment]
@arshaw
Hi, 
I think this issue has been resolved, but I'm still having problems.
The entire screen will be long, especially if there is a long popover at the bottom of the calendar.
I want popovers to fit in my calendar, are there any plans to do this?

Regards,

version: 5.10.0
https://codepen.io/qlgctaoz/pen/VwzrbXa
