### ISSUE TITLE
naturalBound is null with CSP

### ISSUE THREAD

**Issue by xi** [fullcalendar/fullcalendar#5556]
I use a strict Content Security Policy (CSP). Since updating to fullcalendar-scheduler 5 the timeline view is not rendered properly and I get the following error:

```
TypeError: naturalBound is null
```

This seems to be caused by this piece of code: https://github.com/fullcalendar/fullcalendar-scheduler/blob/9bc55cc974b53147bd515a133484ae5b621e6534/scrollgrid/src/StickyScrolling.ts#L154

I am not sure how this is connected to the CSP, but the error goes away when I remove the CSP.

Unfortunately, **CodePen/JSFiddle ignore the CSP**, so here is the code for reproducing the issue:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'nonce-2726c7f26c' cdn.jsdelivr.net; style-src cdn.jsdelivr.net" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.1.0/main.css">
  </head>
  <body>
    <div class="calendar"></div>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.1.0/main.js"></script>
    <script nonce="2726c7f26c">
      var el = document.querySelector('.calendar');
      var calendar = new FullCalendar.Calendar(el, {
        schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives',
        initialView: 'timeline',
        events: [{
          start: '2020-06-29 13:00',
          end: '2020-06-29 15:00',
        }, {
          start: '2020-06-29 14:00',
          end: '2020-06-29 16:00',
        }]
      });
      calendar.render();
    </script>
  </body>
</html>
```

**Comment by acerix** [comment]
Thanks for the report, I get the same error in Firefox and similar in Chrome.

I believe the issue comes from the font and inline CSS that are blocked by CSP so I reponed the issue for CSP compliance: 
 https://github.com/fullcalendar/fullcalendar/issues/4317 for CSP compliance

**Comment by xi** [comment]
This is definitely related to the CSP but I also believe there is an issue in the javascript code: The code that triggers the error does not check if `naturalBound` is null. There should either be a check of the code that defines `naturalBound` should make sure that it never is null in the first place.

**Comment by arshaw** [comment]
this is queued for release but please see my comment here: https://github.com/fullcalendar/fullcalendar/issues/4317#issuecomment-664790881

**Comment by arshaw** [comment]
fixed in 5.2.0

**Comment by xi** [comment]
I have just updated and confirm this is fixed. Thank you!

**Comment by stefanuebe** [comment]
We somehow still have this issue in 5.8.0. Is there additional work to be done beside using the latest version?

```
Uncaught TypeError: Cannot read property 'top' of null
    at eval (main.js?1dfc:273)
    at Array.map (<anonymous>)
    at StickyScrolling.computeElDestinations (main.js?1dfc:254)
    at StickyScrolling.updateSize (main.js?1dfc:195)
    at eval (main.js?1dfc:809)
    at Array.forEach (<anonymous>)
    at ScrollGrid.updateStickyScrolling (main.js?1dfc:809)
    at ScrollGrid.eval (main.js?1dfc:530)
```
