### ISSUE TITLE
Time slots not aligned to labels with dayMinWidth and Bootstrap theme

### ISSUE THREAD

**Issue by Benzidrine** [fullcalendar/fullcalendar#5600]
**Recreation**
 https://codepen.io/Benzid/pen/mdVLxGY

**Screenshot**
![image](https://user-images.githubusercontent.com/14697373/87019046-b628b400-c204-11ea-902e-0bb3a5e63c31.png)

**Explanation**
When using any dayMinWidth value with the bootstrap theme in the ResourceTimeGridDay view, the horizontal lines will not be aligned to the times. This misalignment causes events to display incorrectly and business hours to be out of whack. This happens with all browsers I checked, Edge, Firefox and Chrome.

**Comment by acerix** [comment]
Thanks, confirmed.  Also tested starting from the bootstrap demo and get the same:

https://codepen.io/acerix/pen/mdVKbEm?editors=0010

**Comment by iiibbbmmm** [comment]
A quick fix.
```css
.fc-timegrid-slot-label-frame, .fc-timegrid-slot-label-cushion{
  line-height: 1;
}
```

**Comment by ETSmukesh** [comment]
Getting the same issue in the resourceVerticalView.
I'm using full-calendar with vue/vuetify.
![image](https://user-images.githubusercontent.com/59353507/87500266-b0eebd80-c679-11ea-84ff-308858fa2cb9.png)

**Comment by arshaw** [comment]
I understand the root cause of this bug. The slots have a min-height of `1.5em`, which I assumed would be taller than the height of any possible text content, but when bootstrap sets the line-height to `1.5`, because of rounding, it is sometimes slightly more than the 1.5em min-height, pushing things out of alignment.

I think the best solution would entail putting `&nbsp;`s within each empty slot

**Comment by 5im0n** [comment]
I'm running the same issue too in the `resourceTimeGridDay` and `resourceTimeGridWeek` views.
As you can see in the screenshot the time slots aren't align at all.

I don't think it is due to Bootstrap, cause i haven't loaded it.

The codepen sample: https://codepen.io/5im0n/pen/abdMEKo

![image](https://user-images.githubusercontent.com/659811/88374661-67e5ea00-cd9a-11ea-898c-83718c581f97.png)

**Comment by iiibbbmmm** [comment]
> I understand the root cause of this bug. The slots have a min-height of `1.5em`, which I assumed would be taller than the height of any possible text content, but when bootstrap sets the line-height to `1.5`, because of rounding, it is sometimes slightly more than the 1.5em min-height, pushing things out of alignment.
> 
> I think the best solution would entail putting `&nbsp;`s within each empty slot

Yes, in that case, my workaround changes to
```css
.fc .fc-timegrid-slot:empty:after {
  content: "\a0";
}
```

**Comment by arshaw** [comment]
implemented in master. will release soon.

thanks @iiibbbmmm , the solution i used was very similar to what you proposed.

**Comment by arshaw** [comment]
the problem originally reported in this ticket has been fixed in v5.2.0: https://codepen.io/arshaw/pen/MWKNVLY?editors=0010

**Comment by mukeshghodela-easternts** [comment]
I Updated to version to 5.2.0 still getting the same issue
![image](https://user-images.githubusercontent.com/59353507/89489226-9e265f00-d7c7-11ea-8314-1dc2a37e0102.png)

**Comment by SvetlozarValchev** [comment]
The issue is still present in 6.1.15

![image](https://github.com/user-attachments/assets/44790223-4cfa-4548-9bc3-313ca5872469)
