### ISSUE TITLE
RRule exclusion doesn't work while adding the 'Z' char for RRule datetimes

### ISSUE THREAD

**Issue by meness** [fullcalendar/fullcalendar#5726]
### Reduced Test Case

https://codesandbox.io/s/fullcalendar-z-char-issue-ubmm7

### Bug Description

I want an event occurring every Saturday, but for only one of those Saturdays, I want to show a completely different event. Everything works fine without the `Z` char in RRule datetimes (i.e. `20200810T103000Z`) but as soon as I add the char it shows both events for that day. Please see [this example](https://codesandbox.io/s/fullcalendar-z-char-issue-ubmm7).

**Comment by acerix** [comment]
Thanks, confirmed.    Same issue in the basic debug template:

https://codepen.io/acerix/pen/MWyjXQX?editors=0010

**Comment by arshaw** [comment]
this has been released in v5.3.1!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.3.1

updated repro: https://codepen.io/arshaw/pen/ExKbvRp?editors=0010

**Comment by meness** [comment]
@arshaw @acerix It seems the issue still exists. Please check this out: https://codepen.io/meness/pen/JjXByJj?editors=0010

I expect `October 03` to be excluded while using `Z` char. Now test it without `Z` char, everything will work as expected!

**Comment by acerix** [comment]
Yes, it seems the issue still exists in this case.

**Comment by arshaw** [comment]
this is fixed in 5.4.0
https://codepen.io/arshaw/pen/JjKwmRK?editors=0010

**Comment by derpdead** [comment]
@arshaw it still doesn't work. Take a look at this: https://codepen.io/yerpy/pen/oNLrJyE?editors=0010 - it suppose to exclude rendering event at 2020-11-20.

**Comment by arshaw** [comment]
@derpdead your exdate didn't have the same time as your original date. that's necessary. when they all have a consistent time, it works: https://codepen.io/arshaw/pen/JjKQgoR?editors=0010

**Comment by derpdead** [comment]
@arshaw good point! I would never notice that. Thanks!

**Comment by sebap100** [comment]
There is a regression produced by the fix in v5.4.0: https://github.com/fullcalendar/fullcalendar/issues/5985
