### ISSUE TITLE
+ more Buttons Hidden Behind Events with dayMaxEventRows

### ISSUE THREAD

**Issue by Marionovello** [fullcalendar/fullcalendar#5771]
### Reduced Test Case

Using FullCalendar V5.3.0
[Here's a link to a Codepen example](https://codepen.io/marionovello/pen/RwaZoXY)

### Bug Description

Similar to #5359 but this example uses multiple events that span months. Like in #5359, I set the backgroundColor to transparent so you can see it easily i.e. the **+ more** buttons are rendered behind events.

### Screenshots
![hidden-more-button](https://user-images.githubusercontent.com/7504219/91740257-4bdf2080-eb70-11ea-90c2-5d99494e7aa8.png)

**Comment by acerix** [comment]
Thanks, confirmed

**Comment by arshaw** [comment]
I made the fix for this and will release it in the next 24 hours

**Comment by arshaw** [comment]
this has been released in v5.3.1!
https://github.com/fullcalendar/fullcalendar/releases/tag/v5.3.1

updated repro: https://codepen.io/arshaw/pen/bGpYrjw?editors=0010

**Comment by arshaw** [comment]
Crap, I now see there's still an issue with the 4th week of events. Will fix this very soon.

**Comment by arshaw** [comment]
was actually a distinct bug: https://github.com/fullcalendar/fullcalendar/issues/5790

it was just fixed in 5.3.2

updated repro: https://codepen.io/arshaw/pen/PoNEawP?editors=0010

everything should be working now if you use 5.3.2 (of daygrid)

**Comment by zhuh911** [comment]
Excuse me,i  have update 5.3.2 (of the @fullcalendar/daygrid plugin)
but I now see there's still an issue
my demo：
dependencies：
"@fullcalendar/core": "^5.3.1",
    "@fullcalendar/daygrid": "^5.3.2",
    "@fullcalendar/interaction": "^5.3.1",
    "@fullcalendar/moment": "^5.3.1",
    "@fullcalendar/timegrid": "^5.3.1",
    "@fullcalendar/vue": "^5.3.1",

code：
dayMaxEventRows: true,
        views: {
          timeGrid: {
            dayMaxEventRows: 3
          },
          dayGrid: {
            dayMaxEventRows: 2
          }
        },

+ more Buttons Hidden Behind Events with dayMaxEventRows

**Comment by MarcoYolanga** [comment]
To anyone who can't update the library, here is a small fix in CSS to make the link visible even when it's overlapped by events:

.fc .fc-daygrid-day-bottom {
    z-index: 6;
}
.fc .fc-daygrid-day-bottom > a{
  border: 1px solid gray;
  border-radius: 3px;
  background: whitesmoke;
  padding-right: 4px;
  margin-top: 3px;
  display: inline-block;
}
