### ISSUE TITLE
Error with eventContent w/ Angular (list view & resource timeline)

### ISSUE THREAD

**Issue by Telio3** [fullcalendar/fullcalendar#7058]
## Bug Description

With version 6, I used the eventContent template. (on Angular 14 and 15)
The render goes well on the view dayGridMonth, timeGridWeek, timeGridDay but not on the list and resource timeline.

This error completely crashes the full calendar actions.

![image](https://user-images.githubusercontent.com/92578579/207630656-88ec5da6-f3f2-4eeb-be47-e2a68f8b640c.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by Telio3** [comment]
> Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Thank you for considering my issue, here is a stackblitz link explaining my problem:
https://stackblitz.com/edit/angular-ivy-6dsw4z?file=src/app/app.component.ts

**Comment by Telio3** [comment]
Thank you for considering my issue, here is a stackblitz link explaining my
problem:
https://stackblitz.com/edit/angular-ivy-6dsw4z?file=src/app/app.component.ts

Le jeu. 15 déc. 2022 à 01:09, Dylan Ferris ***@***.***> a
écrit :

**Comment by arshaw** [comment]
I can reproduce this with list view but no resource timeline. updated repro:
https://stackblitz.com/edit/angular-ivy-5ks6m5?file=package.json,src%2Fapp%2Fapp.component.ts

**Comment by arshaw** [comment]
Working okay in v5. This seems like a regression.
https://stackblitz.com/edit/github-jfnn7z?file=src%2Fapp%2Fapp.component.ts

**Comment by Telio3** [comment]
> Working okay in v5. This seems like a regression. https://stackblitz.com/edit/github-jfnn7z?file=src%2Fapp%2Fapp.component.ts

Yes, it worked in previous versions.
But eventContent template is very interesting for my use.

**Comment by arshaw** [comment]
Fixed in [v6.0.1](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.1)

Updated working repro:
https://stackblitz.com/edit/angular-ivy-2jddo7?file=package.json,src%2Fapp%2Fapp.component.ts

**Comment by hoangdinhcong** [comment]
Hi @arshaw , 

Thank you for this upgrade 🔥. 
I updated my repo to v6.0.1. Seem like everything works. But the errors I mentioned before still happened 😢  
Please take a look. Thank you so much.

My issue: https://github.com/fullcalendar/fullcalendar-angular/issues/426#issuecomment-1352627608
Here is my updated repo: https://stackblitz.com/edit/github-msefaz?file=src%2Fapp%2Fmy-calendar%2Fmy-calendar.component.html


> An error occurs when I close the dialog which has fullcalendar inside:
> ```text
> preview-d0bbfde89eb2a.js:2 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
>     at TransportContainerComponent.ngOnDestroy (https://github-msefaz.stackblitz.io/turbo_modules/@fullcalendar/angular@6.0.1/fesm2015/fullcalendar-angular.mjs:164:24)
>     at executeOnDestroys (https://github-msefaz.stackblitz.io/turbo_modules/@angular/core@15.0.4/fesm2015/core.mjs:6454:32)
>     at cleanUpView (https://github-msefaz.stackblitz.io/turbo_modules/@angular/core@15.0.4/fesm2015/core.mjs:6364:9)
>     at destroyViewTree (https://github-msefaz.stackblitz.io/turbo_modules/@angular/core@15.0.4/fesm2015/core.mjs:6197:17)
>     at destroyLView (https://github-msefaz.stackblitz.io/turbo_modules/@angular/core@15.0.4/fesm2015/core.mjs:6342:9)
>     at ViewContainerRef.remove (https://github-msefaz.stackblitz.io/turbo_modules/@angular/core@15.0.4/fesm2015/core.mjs:22721:13)
>     at ViewContainerRef.clear (https://github-msefaz.stackblitz.io/turbo_modules/@angular/core@15.0.4/fesm2015/core.mjs:22564:18)
>     at NgIf._updateView (https://github-msefaz.stackblitz.io/turbo_modules/@angular/common@15.0.4/fesm2015/common.mjs:3540:37)
>     at set ngIf [as ngIf] (https://github-msefaz.stackblitz.io/turbo_modules/@angular/common@15.0.4/fesm2015/common.mjs:3507:14)
> ```

**Comment by hoangdinhcong** [comment]
Hi @arshaw ,

I realized that the collapse button in the resources left panel also doesn't work and occurs the same error.
I've updated my repo. Please take a look. Thank you so much:
https://stackblitz.com/edit/github-msefaz?file=src%2Fapp%2Fmy-calendar%2Fmy-calendar.component.html


![image](https://user-images.githubusercontent.com/6839256/209052854-30176a9d-7017-4a38-a181-c9c70874f20f.png)

**Comment by arshaw** [comment]
@hoangdinhcong , i've made a separate ticket for your issue:
https://github.com/fullcalendar/fullcalendar/issues/7105
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
