### ISSUE TITLE
Dragging events during ongoing backend requests results in duplicate events

### ISSUE THREAD

**Issue by mparkki** [fullcalendar/fullcalendar#7067]
### Reduced Test Case

https://codesandbox.io/s/test-react-redux-typescript-forked-q05tx?file=/src/calendar.tsx

### Bug Description

We're currently banging our heads against the wall with an issue with duplicate events whenever a user has **_initiated a drag and drop_** while an **_update to the redux state_** occurs. We've looked through examples/documentation on how to make FullCalendar work together with React/Redux (including https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/react-redux by @arshaw ), but are still unable to figure out how we should fix the issue on our end.

Steps to reproduce:
1. Drag and drop the event in the calendar to another time/day
2. Immediately after dropping the event at another time/day, click and move the event to another time/day _**without releasing it**_
3. Wait for a few seconds, and then drop the event

**Expected behaviour:**
- Only a single instance of the event is present in the calendar

**Actual behaviour:**
- **_Two_** events are present in the calendar. In other words, the event has been **_duplicated_**.

---

Is this an issue with FullCalendar itself? Or are we using FullCalendar in the wrong way?

Help is greatly appreciated.

**Comment by arshaw** [comment]
Fixed since [v6.1.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.0)

Update repro: https://codesandbox.io/s/test-react-redux-typescript-forked-xki0xc?file=/src/calendar.tsx

(drag the event around rapidly and you'll see duplicate events no longer get created. you will still see the delay in movement because of the delay of the request, but that's expected).

Please ensure that every event object has an `id` property. This is used identify same event objects between renders where the event array changes. Similar to how `key` works in React.

Please also ensure you use [toPlainEvent](https://fullcalendar.io/docs/Event-toPlainObject) when spreading an EventApi's props into your redux store.

I have a note-to-self to make this all clearer in the docs

**Comment by arshaw** [comment]
That updated repro is still showing some problems. I'll revisit.

**Comment by pauldvu** [comment]
@arshaw Thanks for the update! I recently solved this issue by lifting state up and was managing my async state manually, but that was a ton of work to get working right. Look forward to implementing changes from v6.1

**Comment by arshaw** [comment]
This is finally fixed in [v6.1.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.3)

Update repro:
https://codesandbox.io/s/test-react-redux-typescript-forked-xki0xc?file=/src/calendar.tsx

It's important for everyone to have unique `id` properties on their events for this to work. Functions almost like a `key` in react. This is on my todo list to document.

@pauldvu, glad you were able to work around the original issue.

**Comment by cuttingedgecrm** [comment]
Using v6.1.4 and React 18 and still seeing this. I have a unique ID set in the eventData of each new Draggable and getting 5 or 6 events on each drop. Any tips?

**Comment by arshaw** [comment]
@cuttingedgecrm, would you mind opening a new ticket?
