### ISSUE TITLE
Bug when toggling allDaySlot and using dayMinWidth - Cannot read properties of undefined

### ISSUE THREAD

**Issue by guicara** [fullcalendar/fullcalendar#7096]
### Reduced Test Case

https://stackblitz.com/edit/github-3jhwzz?file=src/DemoApp.jsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Hello,

First of all, thank you for this great library! I'm using the premium version of Fullcalendar v5 on a React project. The following bug is visible with React (not tested with vanilla JavaScript). When it occurs, React renders a blank page and errors are visible in the JavaScript console.

Please see the provided [reduced test case](https://stackblitz.com/edit/github-3jhwzz?file=src/DemoApp.jsx) on Stackblitz.

You can try to toggle the "toggle allDaySlot" on the left sidebar. The calendar throws errors if `dayMinWidth` is used.

```
main.js:14368 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at ScrollGrid.getChunkConfigByIndex (main.js:14368:53)
    at ScrollGrid._handleChunkEl (main.js:14383:32)
    at RefMap.handleValue (main.js:9173:27)
    at refCallback.callbackMap.<computed> (main.js:9186:23)
    at safelyDetachRef (main.js:40783:20)
    at commitMutationEffectsOnFiber (main.js:42221:13)
    at recursivelyTraverseMutationEffects (main.js:42143:7)
    at commitMutationEffectsOnFiber (main.js:42216:9)
    at recursivelyTraverseMutationEffects (main.js:42143:7)
    at commitMutationEffectsOnFiber (main.js:42216:9)
    
main.js:14368 Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at ScrollGrid.getChunkConfigByIndex (main.js:14368:53)
    at ScrollGrid._handleChunkEl (main.js:14383:32)
    at RefMap.handleValue (main.js:9173:27)
    at refCallback.callbackMap.<computed> (main.js:9186:23)
    at safelyDetachRef (main.js:40783:20)
    at commitMutationEffectsOnFiber (main.js:42221:13)
    at recursivelyTraverseMutationEffects (main.js:42143:7)
    at commitMutationEffectsOnFiber (main.js:42216:9)
    at recursivelyTraverseMutationEffects (main.js:42143:7)
    at commitMutationEffectsOnFiber (main.js:42216:9)

main.js:36562 The above error occurred in the <th> component:

    at th
    at tr
    at tfoot
    at table
    at ScrollGrid (https://github3jhwzz-zjpb--8080.local-credentialless.webcontainer.io/main.js:14011:47)
    at div
    at MountHook (https://github3jhwzz-zjpb--8080.local-credentialless.webcontainer.io/main.js:5717:47)
    at ViewRoot (https://github3jhwzz-zjpb--8080.local-credentialless.webcontainer.io/main.js:5772:47)
    at DayTimeColsView (https://github3jhwzz-zjpb--8080.local-credentialless.webcontainer.io/main.js:15701:47)
    at div
    at ViewContainer (https://github3jhwzz-zjpb--8080.local-credentialless.webcontainer.io/main.js:8073:47)
    at CalendarContent (https://github3jhwzz-zjpb--8080.local-credentialless.webcontainer.io/main.js:8218:47)
    at div
    at CalendarRoot (https://github3jhwzz-zjpb--8080.local-credentialless.webcontainer.io/main.js:8384:47)
    at CalendarDataProvider (https://github3jhwzz-zjpb--8080.local-credentialless.webcontainer.io/main.js:7618:28)
    at FullCalendar (https://github3jhwzz-zjpb--8080.local-credentialless.webcontainer.io/main.js:13449:47)
    at div
    at div
    at DemoApp (https://github3jhwzz-zjpb--8080.local-credentialless.webcontainer.io/main.js:16011:5)
```

https://user-images.githubusercontent.com/2470367/208537874-6e407e5f-b974-41b4-9c82-49ee6d0348c8.mp4

<img width="1728" alt="Screenshot 2022-12-19 at 23 23 28" src="https://user-images.githubusercontent.com/2470367/208538401-65d779a2-91cc-4a2d-aff7-6f178382498f.png">

**Comment by arshaw** [comment]
Similar in nature to #6967

NOTE: this bug is with v5 codebase, maybe v6 as well

**Comment by acerix** [comment]
Also reported in https://fullcalendar.freshdesk.com/a/tickets/5842

It seems this is been fixed in v6 as I tried the same there.

https://stackblitz.com/edit/github-ebnzps?file=src%2FDemoApp.jsx

**Comment by guicara** [comment]
Hello @acerix,

Thanks for your reply and email.

I've just upgraded my project to Fullcalendar v6. It was quite easy.

Unfortunately, the bug is still visible. At first, I didn't understand because in your reduced test case it's working. You have only used the `dayMinWidth` and `allDaySlot` props on the `FullCalendar` component, which makes sense since I initially reported this bug when using these two props in conjunction.

By adding prop by prop on your test case to match my code base, it seems that the `stickyFooterScrollbar` set to `true` trigger the same bug.

Here is another reduced test case:
https://stackblitz.com/edit/github-ebnzps-tbw8lu?file=src%2FDemoApp.jsx

Strange, isn't it?

**Comment by guicara** [comment]
So it seems that the prop `stickyFooterScrollbar` set to `true` was not needed for my project. The horizontal scrollbar is visible when needed. Setting this parameter to `true` or not using it at all is the same in my use case. I don't remember why I added it in the first place.

_TL;DR: the bug is still there and it can be important to fix it for other Fullcalendar's users. In my case, I've found a workaround_

**Comment by acerix** [comment]
Thanks for the details, yes, it seems this bug only happens with `stickyFooterScrollbar` and is the same in v6.
