### ISSUE TITLE
dot-event element from eventDidMount does not exists in the DOM in dayGridMonth view for Vue2/Angular

### ISSUE THREAD

**Issue by Yaty** [fullcalendar/fullcalendar#7191]
### Reduced Test Case

https://stackblitz.com/edit/github-anq735?file=src/DemoApp.vue

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

Hello,

I'm using full-calendar 6.1.1 (and 6.1.2 for the vue connector).

I found out that when I'm on the `dayGridMonth` view, the `fc-daygrid-dot-event` elements passed inside the `eventDidMount` hook does not exists in the DOM, this prevents me from attaching a tooltip on it.

There are no problems with `fc-daygrid-block-event`. I don't have the issue on 6.0.2.

Thanks!

**Comment by stefanomiccoli** [comment]
I have the same issue with angular.

**Comment by arshaw** [comment]
Not fixed in v6.1.3 ([updated repro](https://stackblitz.com/edit/github-anq735-adwmvz?file=package.json,src%2FDemoApp.vue))

Moving to next bugfix milestone

**Comment by Alex-Doro** [comment]
Similar issue on Angular, had to roll back to v5.
Full-calendar seems to have the full list of events that need to rendered, however, after any re-render `customRenderingArray` and `customRenderingMap` seem to contain way less events. Seems like any event that has a similar start time with other events is cut off and only one of them actually gets rendered

**Comment by arshaw** [comment]
Version [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5) (just released) fixed this bug and you can see proof in the above modified reproduction.

Please post here if any further issues about this.

**Comment by Yaty** [comment]
Hi @arshaw, thanks for the update, unfortunately I think the issue still remains. I'm using your reproduction.

For block events it's working properly as before, when I select the node that is printed in the console my browser can correctly find it : 
![image](https://user-images.githubusercontent.com/11981803/226866914-5e20a7c0-30b9-4aa0-ba7b-af4091c3cbb9.png)

However for dot events it seems the element passed through eventDidMount is no where on the document, i.e if I select the node printed in the console, it does not exists/the browser cannot find it : 
![image](https://user-images.githubusercontent.com/11981803/226867149-bfdbe496-7074-4ce3-93a3-3e41f805c54b.png)

So this prevents me from manipulating the element (attaching a tooltip in my case).
I use Firefox 111.

**Comment by Alex-Doro** [comment]
The problem in Angular with `customRenderingArray` and `customRenderingMap` cutting off events persists for me as well

**Comment by arshaw** [comment]
I'll reinvestigate for the next bugfix release

**Comment by arshaw** [comment]
This is fixed "for real" in [v6.1.9](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.9)

Could anyone from this thread verify please?

**Comment by Yaty** [comment]
looks good on my side, thanks @arshaw !

**Comment by TheStateOfComedy** [comment]
Still Have issues with this in version 6.1.15
![image](https://github.com/user-attachments/assets/f2d4d3e2-7003-47fe-934d-d5a9eb17fed9)
