### ISSUE TITLE
React + Vite css doesn't seem to be working properly

### ISSUE THREAD

**Issue by joao-azevedo-toptal** [fullcalendar/fullcalendar#7238]
### Reduced Test Case

https://stackblitz.com/edit/vitejs-vite-9ygsyj?file=src%2FApp.tsx,src%2Findex.css,package.json&terminal=dev

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

When using Vite with React the styles for the calendar are not working properly, causing issues like the events not taking all the days they should.

**Comment by arshaw** [comment]
@joao-azevedo-toptal and @acerix , can you be more specific about exactly how its not rendering correctly?

**Comment by acerix** [comment]
For example, "Conference" should be 2 days but only shows the first day.  There is also some padding missing in the day cells.

![screen](https://user-images.githubusercontent.com/379534/224457046-258fef74-e450-4716-b472-8b39754219be.png)

**Comment by joao-azevedo-toptal** [comment]
Doesn't seem to be related to vite, I'm having the same issue with a  create react app project
https://stackblitz.com/edit/node-9de2zk?file=src%2FApp.js

**Comment by arshaw** [comment]
@joao-azevedo-toptal , the staged fix will almost definitely fix the issue you describe as well.

**Comment by arshaw** [comment]
Fixed in [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5)

Updated vite repro: https://stackblitz.com/edit/vitejs-vite-agartk?file=package.json&terminal=dev
Updated CRA repro: https://stackblitz.com/edit/node-6ywegt?file=package.json

**Comment by c0d3m3nt0r** [comment]
Still seeing the same issue in v6.1.5, not sure what else to do, styles only load while in development mode, in my case, there are six style tags rendered when it all looks good, but for some reason when building for production environment, and then loading the same page, only two out of six style tags are being rendered, causing the layout of the calendar to break, the most visible part is the calendar items, which loose ---fc-small-font-size, to consider one single example of all the ones that are missing. I am using next.js, and building with babel, in a typescript project, react is also latest 18.x, and fullcalendar is 6.1.5 (latest as of today). I will keep looking into the code to see that might be missing, but, it is quite strange to have a development version behaving different than a prod one, at this point I have wasted a couple of days without a clue about what might be wrong.
