### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications error in Chrome with `height="auto"` in v7

### ISSUE THREAD

**Issue by acerix** [fullcalendar/fullcalendar#7929]
### Reduced Test Case

https://codesandbox.io/p/devbox/gabi-full-calendar-forked-nzlsx5

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [x] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

In React project using v7 and `height="auto"`, "ResizeObserver loop completed with undelivered notifications." error is displayed in Chrome dev console.  

The codesandbox.io demo shows the error in the built-in console. It seems to happen about half the time,  clicking "refresh" a few times should show the error. 

![Image](https://github.com/user-attachments/assets/73be241f-44ad-40bc-8952-0e5d1fe9114d)

Reported in https://fullcalendar.freshdesk.com/a/tickets/10513

**Comment by arshaw** [comment]
this should be fixed in the latest v7 (currently rc.1)
repro: https://stackblitz.com/edit/github-zwmup7gq?file=src%2Findex.css,src%2FDemoApp.jsx,package.json

**Comment by Jardel-Machado** [comment]
Even when using version `npm i @fullcalendar/angular@7.0.0`, the "ResizeObserver loop completed with undelivered notifications" problem persists.

<img width="1243" height="668" alt="Image" src="https://github.com/user-attachments/assets/2b8ead53-5743-42b7-a0e4-2b307a7b49a6" />
